# Generated by Django 4.2.23 on 2025-08-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_date', models.DateField(unique=True)),
                ('meal_choice1', models.CharField(max_length=200)),
                ('meal_choice2', models.CharField(max_length=200)),
                ('meal_choice3', models.CharField(blank=True, max_length=200)),
                ('meal_choice4', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
